= Example: Integration of Neo4j-GraphQL-Java into a Spring Boot  application using Springs GraphQL

== Overview

This example uses the https://docs.spring.io/spring-graphql/docs/1.0.0-SNAPSHOT/reference/html/[Springs new GraphQL library]

In the link:src/main/java/org/neo4j/graphql/examples/graphqlspringboot/config/Neo4jConfiguration.java[Neo4jConfiguration]
a DataFetchingInterceptor is created, which will be bound to all fields augmented by the neo4j-graphql-library.
Its purpose is the execution of the cypher query and the transformation of the query result.

In the link:src/main/java/org/neo4j/graphql/examples/graphqlspringboot/config/GraphQLConfiguration.java[GraphQLConfiguration]
the type definitions of link:src/main/resources/neo4j.graphql[schema] are loaded and augmented.

In this example some fields of the enhanced type (neo4j) are extended with
link:src/main/java/org/neo4j/graphql/examples/graphqlspringboot/datafetcher/AdditionalDataFetcher.java[custom data fetcher] whose link:src/main/resources/graphql/schema.graphqls[schema is separately defined].

With This in place you can

== Run the example

1. link:src/main/resources/application.yaml[configure your neo4j db] or use a public one
2. run the link:src/main/java/org/neo4j/graphql/examples/graphqlspringboot/GraphqlSpringBootApplication.java[spring boot application]
3. open http://localhost:8080/graphiql to run some graphql queries e.g. try:

```graphql
query{
  other
  movies (options: {limit: 3}){
    title
    bar
    javaData {
      name
    }
  }
}
```
